# Permalinks
permalink:        none

# Setup
title:            I/O studio
url:              http://192.168.1.37/eyeohstudio.github.io

author:
  name:           'Eye Oh Design Studio, SL'
  url:            http://wearestudio.io

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/eyeohstudio/eyeohstudio.github.io

# Collections
collections:
  projects:
    output: true
    values:
      layout: project
