# Permalinks
permalink:        pretty

# Setup
title:            I/O studio
url:              http://wearestudio.io

author:
  name:           'I/O studio'
  url:            http://wearestudio.io

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/eyeohstudio/eyeohstudio.github.io
